from alembic import op
import sqlalchemy as sa



"""create_setting_table

Revision ID: 056a08e481c4
Revises: 52be103db4fd
Create Date: 2023-02-05 11:57:46.058770

"""

# revision identifiers, used by Alembic.
revision = '056a08e481c4'
down_revision = '52be103db4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('first_address', sa.String(length=255), nullable=False),
    sa.Column('second_address', sa.String(length=255), nullable=True),
    sa.Column('first_phone', sa.String(length=255), nullable=False),
    sa.Column('second_phone', sa.String(length=255), nullable=True),
    sa.Column('first_email', sa.String(length=255), nullable=False),
    sa.Column('second_email', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
