from alembic import op
import sqlalchemy as sa



"""create_slider_table

Revision ID: 21441e3c4784
Revises: 4192162044d8
Create Date: 2023-02-10 09:29:46.678874

"""

# revision identifiers, used by Alembic.
revision = '21441e3c4784'
down_revision = '4192162044d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sliders',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('description', sa.String(length=755), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sliders')
    # ### end Alembic commands ###
