from alembic import op
import sqlalchemy as sa



"""create_about_table

Revision ID: 52be103db4fd
Revises: d27a4fff00a0
Create Date: 2023-02-05 11:57:11.063960

"""

# revision identifiers, used by Alembic.
revision = '52be103db4fd'
down_revision = 'd27a4fff00a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission', sa.String(length=1000), nullable=True),
    sa.Column('vision', sa.String(length=1000), nullable=True),
    sa.Column('company_description', sa.String(length=1000), nullable=True),
    sa.Column('ceo_message', sa.String(length=1000), nullable=True),
    sa.Column('policy', sa.String(length=1000), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about')
    # ### end Alembic commands ###
