from alembic import op
import sqlalchemy as sa



"""create_programme_table

Revision ID: 5923f97c796d
Revises: 161c25f03067
Create Date: 2023-02-04 23:38:06.257699

"""

# revision identifiers, used by Alembic.
revision = '5923f97c796d'
down_revision = '161c25f03067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programmes',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('description', sa.String(length=755), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programmes')
    # ### end Alembic commands ###
