from alembic import op
import sqlalchemy as sa



"""create_areas_table

Revision ID: 5a575141faf6
Revises: 056a08e481c4
Create Date: 2023-02-05 11:58:20.268999

"""

# revision identifiers, used by Alembic.
revision = '5a575141faf6'
down_revision = '056a08e481c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('description', sa.String(length=755), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('areas')
    # ### end Alembic commands ###
