from alembic import op
import sqlalchemy as sa



"""create_teams_table

Revision ID: d27a4fff00a0
Revises: 5923f97c796d
Create Date: 2023-02-05 10:13:13.097517

"""

# revision identifiers, used by Alembic.
revision = 'd27a4fff00a0'
down_revision = '5923f97c796d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=155), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=200), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
