from alembic import op
import sqlalchemy as sa



"""added_is_featured_to_programme

Revision ID: dbe427241b04
Revises: ebdd593a054c
Create Date: 2023-02-10 09:13:38.086738

"""

# revision identifiers, used by Alembic.
revision = 'dbe427241b04'
down_revision = 'ebdd593a054c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programmes', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
